/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed709b03-c30a-476d-8d8a-e2c2e82f8a41",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NTKAHfZzG",
    "aws_user_pools_web_client_id": "6l8gvrc0j978d2chgvf7bvm6ig",
    "oauth": {
        "domain": "oswjn-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://oswjn-staging.auth.us-east-1.amazoncognito.com/oauth2/idpresponse",
        "redirectSignOut": "http://localhost:3000/,https://oswjn-staging.auth.us-east-1.amazoncognito.com/oauth2/idpresponse",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://uxxrirfdejf6remym4fkjyjoka.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zhmybpc3mnct5etp33l6iycmli"
};


export default awsmobile;
